### ISSUE TITLE
Rename variables 

### ISSUE THREAD

**Issue by asmorodskiy** [777dimas/Python#1]
1. read1 = config.get('Options', 'Serial') to serialValue
2. read2 = config.get('Options', 'ServerIP') to serverIPValue
3. read3 = config.get('Options', 'Serial') to serialValueOriginal
4. read4 = config.get('Options', 'ServerIP') serverIPValueOriginal

**Comment by 777dimas** [comment]
Realy good)

**Comment by asmorodskiy** [comment]
done !
